export enum ErrorCodes {
  TOKEN_NOT_PROVIDED = 'token-not-provided',
  INVALID_TOKEN = 'invalid-token',
  INVALID_CREDENTIALS = 'invalid-credentials',
  USER_NOT_AUTHENTICATED = 'user-not-authenticated',
  USER_NOT_CREATED = 'user-not-created',
  FORBIDDEN = 'forbidden',
  USER_NOT_FOUND = 'user-not-found',
  EMAIL_ALREADY_EXISTS = 'email-already-exists',
  WORKOUT_NOT_FOUND = 'workout-not-found',
  ID_NOT_PROVIDED = 'id-not-provided',
  INPUT_NOT_PROVIDED = 'input-not-provided',
  INVALID_QUERY = 'invalid-query',
  INVALID_ENTITY = 'invalid-entity',
  INSUFFICIENT_PRIVILEGE = 'insufficient-privilege',
  NOT_NULL_VIOLATION = 'not-null-violation',
}
